# Introduction {.unnumbered}

The purpose of `DownClim` is to offer a tool for regional and national climate projections including the mechanistic 'dynamic' downscaling of the CORDEX initiative. `DownClim` is opposed to the direct statistical downscaling of global climate projections found in WorldClim and CHELSA. `DownClim` is directly inspired of AFRICLIM [@platts2014]. The approach is justified by an improvement in regional projections of CORDEX compared to CMIP (insert few references), although it can increase uncertainty and sometimes be less reliable (insert indian monsoon reference). The tool is an automated `snakemake` workflow easily reproducible and scalable associated to `conda` environments for enhance reproducibility and portability.

As a first step we will develop the pipeline for three study countries (French Guiana, Ivory Coast and New Caledonia) over three continents, with a single baseline (CHELSA V2) and a reduced number of global (GCM) and regional (RCM) climate models for a few scenarios (RCP or SSP). Behind the choice of countries we have different hypotheses. (1) we expect New Caledonia regional topography to be important for projections. (2) we expect Ivory Coast regional climates to be important for projections. (3) we assume French Guiana to be a control with mainly lowland and homogeneous climate. To demonstrate the aim of the tool, we want to validate and/or assess the projections for each country using (1) projections on observed year (e.g. 2005\>2020, even if the differences between scenarios will not be significant), and (2) the difference with forest climatic extent with this product versus classical products.

## Poeple

-   Sylvain Schmitt (sylvain.schmitt\@cirad.fr)
-   Ghislain Vieilledent (ghislain.vieilledent\@cirad.fr)
-   Thomas Arsouze (thomas.arsouze\@cirad.fr)
-   Achille Mauri (mauri.achille\@gmail.com)
