# Literature {.unnumbered}

## To read

-   @brown2008: review downscaling for Africa (dynamical & statistical, bias correction, advantages, best practices)
-   @quintanaseguí2010: comparing statistical downscaling and bias correction: statistical, quantile mapping, anomaly for hydrology
-   @tabor2010: downscaling for conservation: CMIP3 with change-factor on CRU
-   @zhang2005: statistically downscaling GCM to station for crop, quantile mapping
-   @gebrechorkos2019: statistical downscaling of GCM for East Africa

## Similar approach

-   @chakraborty2020
    -   Euro-CORDEX
    -   ECLIPS (European CLimate Index ProjectionS)
    -   80 annual, seasonal and monthly climate variables for two past (1961--1990 and 1991--2010) and five future (2011--2020, 2021--2140, 2041--2060, 2061--2080 and 2081--2100) periods
    -   five regional climate models (RCMs)
    -   RCP 4.5 and RCP 8.5
    -   ECLIPS 1.1 at 0.11° (RCM native)
    -   ECLIPS 2.0 30 arcsec downscaled with delta approach
    -   tested against independent station data from the European Climate Assessment (ECA) dataset
    -   ECLIPS 2.0 (CC 0.78-0.93) \> ECLIPS 1.1 (CC 0.36-0.78)
    -   Cited: 13
-   @shen2020 - EA-CORDEX - Bias Correction and Ensemble Projections of Temperature Changes over Ten Subregions in CORDEX East Asia - three common bias correction methods: variance scaling, additive scaling, and quantile mapping based on empirical distribution - two multi-model averaging methods:
    -   Bayesian model averaging (BMA)
    -   simple multi-model averaging (SMA) - calibrating historical (1980--2005) - Future (2006--49) temperature trends - RCP 4.5 and 8.5 - CRU validation
-   @mcginnis2021 - NA-CORDEX - Five of the major variables used by impacts researchers as well as decision makers have also been bias-corrected - Directly hosted with CORDEX outputs (included on ESGF) - Each RCM community as different experiments corresponding to their questions (ex USA, EU, CA) - Cannon's MBCn algorithm to bias-correct the data, a multivariate quantile-mapping approach that has good all-around performance for multiple uses and corrects the relationships between variables as well as their individual distributions
-   @falco2018 - SAM-CORDEX - 1990 to 2004 - 0.44° - monthly precipitation and 2-m-temperature - RCM - GCM - ERAi - CRU, UDEL, CPC-UNI evaluation
-   A tremendous amount of country / region specific applications

## Examples

-   @gebrechorkos2023:
    -   What: statistically downscaled CMIP6
    -   Resolutions: 0.25° (28km) and daily
    -   How: BCCAQ
    -   Baseline: MSWX & MSWEP
    -   Projections: 18 CMIP6 GCMs
    -   Scenarios: SSP2-4.5, SSP5-3.4-OS & SSP5-8.5
    -   Variables: daily precipitation, air-temperature, maximum and minimum temperature, wind speed, air pressure, and relative humidity
    -   Tool: ClimDown R package
    -   Evaluation: Pearson, RMSE, bias, SE, Taylor diagram
    -   Access: [CEDA](https://catalogue.ceda.ac.uk/uuid/c107618f1db34801bb88a1e927b82317)
    -   Note: remove bias & reproduce extreme events
-   @navarro-racines2020:
    -   What: statistically downscaled CMIP6
    -   Resolutions: 30" (1km) and 30-year means
    -   How: delta method
    -   Baseline: WorldClim
    -   Projections: 35 CMIP5 GCM
    -   Scenarios: RCP 2.6, 4.5, 6.0 & 8.5
    -   Variables: mean monthly maximum and minimum temperatures and monthly rainfall
    -   Tool: ArcGIS & [R](https://figshare.com/articles/software/Delta_Method_Downscaling_Version_1_0/5236471/4)
    -   Evaluation: perfect sibling
    -   Access: WDCC, CCAFS-Climate
    -   Note: thin-plate splines interpolation, Probability Density Function (PDF) comparisons
-   @platts2014:
    -   What: statistically downscaled CORDEX CMIP5
    -   Resolutions: 30" (1km) and 20-year means
    -   How: change-factor (= delta method)
    -   Baseline: CRU, WorldClim, TAMSAT, CHIRPS
    -   Projections: 8 GCM CMIP5 x 2 RCM CORDEX
    -   Scenarios: RCP4.5 & RCP8.5
    -   Variables: monthly 2-m air temperature (mean, minimum and maximum) and monthly rainfall
    -   Tool: R & GRASS GIS
    -   Evaluation: No
    -   Access: [York University](https://webﬁles.york.ac.uk/KITE/AfriClim/)
    -   Note: spline-interpolated

## Downscaling

### Bias correction

-   delta or change-factor [@platts2014; @navarro-racines2020]

### Statistical

-   SDSM: Statistical DownScaling Model [@wilby2002; @wilby2012]

### Quantile

-   BCCAQ: Bias Correction Constructed Analogues with Quantile mapping reordering [@cannon2015; @werner2016]
-   CA: Constructed Analogues [@maurer2010]
-   CI: Climate Imprint [@hunter2005]
-   DQM: Quantile Delta Mapping [@cannon2015]
-   CDFt: cumulative distribution function transform (R CDFt) [@lanzante2019]

### Other

-   TLFN: time-lagged feed-forward neural network or temporal neural network [@coulibaly2005]
-   kriging (KrigR) [@davy2021]
-   Dynamical downscaling (RCM)

## Climate data

<https://climatedataguide.ucar.edu/type/satellite-data-products>

### Reanalysis

-   ERA5-Land: reanalysis dataset from European Centre for Medium-Range Weather Forecasts (ECMWF) [@muñoz-sabater2021]
    -   Resolutions: 0.1° (9km) & hourly (daily and monthly averages)
    -   Period: 1950-present
    -   Area: global
    -   Variables: 53 including temperature and precipitation
    -   Provider: [CDS](https://cds.climate.copernicus.eu/cdsapp#!/search)
    -   Projections: No (but CMIP & CORDEX on CDS)
    -   Tools: python cdsapi, R ewcmfr
    -   Note:
-   CHELSA 2.1: Climatologies at High resolution for the Earth's Land Surface Areas [@karger2017]
    -   Resolutions: 30" (1km) & 20-year means (daily & monthly available)
    -   Period: 1981-2100
    -   Area: global
    -   Variables: pr, rsds, tas, tasmax, tasmin, bioclim
    -   Provider: [CHELSA](https://chelsa-climate.org/)
    -   Projections: downscaled CMIP5 & CMIP6
    -   Tools: R ntbox, chelsaDL
    -   Note:
-   WorldClim 2: 1-km spatial resolution climate surfaces for global land areas [@fick2017]
    -   Resolutions: 30" (1km) & 30-year means
    -   Period: 1970-2000
    -   Area: global
    -   Variables: tasmin, tasmax, tas, pr, rsds, ws, vapr, bioclim
    -   Provider: [WorldClim](https://www.worldclim.org/)
    -   Projections: CMIP6 23 GCM 4 SSP 20-year means
    -   Tools: R raster & geodata
    -   Note:
-   CRU TS 4: monthly high-resolution gridded multivariate climate dataset (Climatic Research Unit Time Series) [@harris2020]
    -   Resolutions: 0.5° (45km) & monthly
    -   Period: 1901--2018
    -   Area: global
    -   Variables: cld, dtr, frs, pet, pre, tmn, tmp, tmx, vap, wet
    -   Provider: [CRU](https://crudata.uea.ac.uk/cru/data/hrg/cru_ts_4.07/)
    -   Projections: No
    -   Tools: R cruts
    -   Note: angular-distance weighting (ADW)
-   CHIRPS: Rainfall Estimates from Rain Gauge and Satellite Observations [@funk2015]
    -   Resolutions: 0.05°(900m) & daily, pentadal, and monthly
    -   Period: 1981-present
    -   Area: global
    -   Variables: rainfall
    -   Provider: [CHIRPS](https://www.chc.ucsb.edu/data/chirps)
    -   Projections: No
    -   Tools: R chirps
    -   Note: infrared Cold Cloud Duration
-   JRA-55: the Japanese 55-year Reanalysis [@kobayashi2016]
    -   Resolutions:
    -   Period: 1958-present
    -   Area: global
    -   Variables:
    -   Provider: [JRA](https://jra.kishou.go.jp/JRA-55/index_en.html#usage)
    -   Projections: No
    -   Tools:
    -   Note:
-   TerraClimate: a high-resolution global dataset of monthly climate and climatic water balance from 1958--2015 [@abatzoglou2018]
    -   Resolutions: 0.04° (4km) & monthly
    -   Period: 1958-2020
    -   Area: global
    -   Variables: Maximum temperature, minimum temperature, vapor pressure, precipitation accumulation, downward surface shortwave radiation, wind-speed
    -   Provider: [TerraClimate](https://www.climatologylab.org/terraclimate.html)
    -   Projections: No
    -   Tools: R TerraClimate
    -   Note: derived variables accessible, derived from WorldClim + CRU TS + JRA55
-   GloH2O MSWX: Multi-Source Weather [@beck2022] & MSWEP: Multi-Source Weighted-Ensemble Precipitation [@beck2017; @beck2019]
    -   Resolutions: 0.1° (9km) & 3-hourly
    -   Period: 1979-present
    -   Area: global
    -   Variables: precipitation
    -   Provider: [GloH2O](https://www.gloh2o.org/mswep/)
    -   Projections: No
    -   Tools:
    -   Note: gauge, ERA5, HydroGFD, PGF, WFDE5, ...

### Observations

-   GHCNd: Historical Climatology Network Daily [@menne2012]
-   GSOD: Global Summary of the Day [@hsparks2017]
-   GPCC: Global Precipitation Climatology Centre [@becker2013]

### Satellite

-   TAMSAT: Tropical Applications of Meteorology using Satellite data and ground-based observations [@maidment2017]
-   CMORPH: Climate Prediction Center morphing technique [@joyce2004]
-   TRMM: Tropical Rainfall Measuring Mission [@kummerow1998]
-   TMPA: Multi-satellite Precipitation Analysis [@huffman2009]
-   GSMaP: Global Satellite Mapping [@okamoto]

## Climate projections

-   CMIP5: the fifth phase of Coupled Model Intercomparison Project [@taylor2012]
-   CORDEX (CMIP5 based): Coordinated Regional Downscaling Experiment [@giorgi2015]
-   CMIP6: the sixth phase of Coupled Model Intercomparison Project [@tokarska2020]
-   CMIP6 HighResMIP: High Resolution Model Intercomparison Project [@haarsma2016; @liang-liang2022]

## Providers

-   [CDS](https://cds.climate.copernicus.eu/cdsapp#!/search): Climate Data Store including CMIP (not HighRes), ERA5-Land, CORDEX (not all), ...
-   ESGF: Earth System Grid Federation for different providers (e.g. UK-CEDA, IPSL, LLNL, ...) including HighResMIP, CMIP, and CORDEX
-   [WDCC](http://www.dkrz.de/): World Data Center for Climate
-   [CCAFS-Climate](http://ccafs-climate.org/): global and regional future high-resolution climate datasets

## Scenarios

-   RCP: Representative Concentration Pathways
    -   Critics of RCP 8.5 used wrongly as buisness as usual in @hausfather2020
-   SSP: Shared Socio-economic Pathways

## Selection

Compromise for computation limitations.

-   \(1\) initial selection of climate models based on the range of projected changes in climatic means, (2) refined selection based on the range of projected changes in climatic extremes and (3) final selection based on the climate model skill to simulate past climate [@lutz2016]
-   envelope approach: representing the diversity of projections
-   past-performance approach: capacity to reproduce past/present climate

## Evaluation

-   TSS: Taylor Skill Score [@liang-liang2022]
-   IA: index of agreement [@gebrechorkos2018]
-   CC: Pearson correlation coefficient
-   RMSE: Root mean square error
-   MAE: Mean absolute error
-   R: Relative bias
-   SD: Standard deviation
-   Taylor diagram [@taylor2001]
-   PS: perfect sibling (@hawkins2013\]
-   Extreme indices from Expert Team on Climate Change Detection and Indices (ETCCDI) [@karl1999]

## Tools

### Standalone

-   SAGA GIS
-   [CDO](https://code.mpimet.mpg.de/projects/cdo): Climate Data Operators
-   singularity

### Python

-   xarray
-   xesmf
-   salem
-   rioxarray
-   snakemake

### R

-   terra
-   netcdf4
-   ClimDown: downscaling with Bias Correction/Constructed Analogues with Quantile mapping reordering (BCCAQ) [@hiebert2018]
-   climdex.pcic: climate extremes indices
-   KrigR [@davy2021]
-   CDFt
-   GSODR [@hsparks2017]
