rule get_cmip6:
    input:
        expand("results/baselines/{area}_{base}_{aggregation}_{period}.nc", 
                area=config["area"],
                period=config["hist_years"],
                aggregation=config["aggregation"],
                allow_missing=True)
    output:
        "results/projections/_CMIP6_world_{institute}_{model}_{experiment}_{ensemble}_none_none_{base}_done.txt"
    log:
        "results/logs/get_cmip6_world_{institute}_{model}_{experiment}_{ensemble}_none_none_{base}.log"
    benchmark:
        "results/benchmarks/get_cmip6_world_{institute}_{model}_{experiment}_{ensemble}_none_none_{base}.benchmark.txt"
    threads: 10
    resources:
        mem_mb=20000
    conda:
        "../envs/xarray.yml"
    params:
        area=config["area"],
        institute="{institute}",
        model="{model}",
        experiment="{experiment}",
        ensemble="{ensemble}",
        base="{base}",
        variables=config["variables"],
        time_frequency=config["time_frequency"],
        periods=all_periods,
        aggregation=config["aggregation"]
    script:
      "../scripts/get_cmip6.py"
